<?php
 // module/Organization/view/organization/organization/edit.phtml:

 $title = 'Edit organization';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'organization',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('address'));
 echo $this->formRow($form->get('post_code'));
 echo $this->formRow($form->get('contact_number'));
 echo $this->formRow($form->get('contact_mail'));
 echo $this->formRow($form->get('contact_person'));
 echo $this->formRow($form->get('contact_web'));
 echo $this->formRow($form->get('esol_assesment'));
 echo $this->formRow($form->get('tutors_qualified'));
 echo $this->formRow($form->get('tutors_qualified_condition'));
 echo $this->formRow($form->get('courses_acreditated'));
 echo $this->formRow($form->get('courses_acreditation_condition'));
 echo $this->formRow($form->get('how_acreditated'));
 echo $this->formRow($form->get('core_curriculum'));
 echo $this->formRow($form->get('core_curriculum_condition'));
 echo $this->formRow($form->get('referral_system'));
 echo $this->formRow($form->get('classes_outside_newham'));
 echo $this->formRow($form->get('other_information'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>
